Add sh check, content checks
Signed-off-by: Bogdan Dobrelya <bdobrelia@mirantis.com>

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -4,6 +4,7 @@
 #
 #    Puppet >= 2.7 is installed on this machine
 #    puppet-lint is installed on this machine
+#    devscripts is installed on this machine
 #    ERB is installed on this machine
 #    git is installed on this machine
 #    sed is installed on this machine
@@ -29,6 +30,27 @@ STATUS=0
 # Register exit trap for removing temporary files
 trap 'rm -rf $TMPFILE' EXIT INT HUP
 
+check_bash() {
+  bash -n "$1" 2>&1
+  if [ $? -ne 0 ]; then
+    echo "bash syntax error in ${2}" >&2
+    STATUS=2
+  fi
+  sed -i -e 's%^#!/bin/bash%#!/bin/sh%g' "$1" >/dev/null 2>&1
+  /usr/bin/checkbashisms "${1}" 2>&1
+  if [ $? -ne 0 ]; then
+    echo "sh syntax error in $2" >&2
+    STATUS=2
+  fi
+}
+
+fix_trailing_ws_and_stage() {
+  # Fix trailing whitespaces
+  echo "### Fixing whitespaces, if any, in $1" >&2
+  sed -i 's/[[:space:]]*$//' "$1"
+  git add "$1"
+}
+
 # Check for Puppet binary
 which puppet >/dev/null 2>&1 || exit 1
 
@@ -41,86 +63,83 @@ which erb >/dev/null 2>&1 || exit 1
 # Get correct git revision
 if git rev-parse --quiet --verify HEAD > /dev/null
 then
-    revision=HEAD
+  revision=HEAD
 else
-    # Initial commit: diff against an empty tree object
-    revision=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+  # Initial commit: diff against an empty tree object
+  revision=4b825dc642cb6eb9a060e54bf8d69288fbee4904
 fi
 
 IFS="
- "
+"
 
 # Get a list of files changed in this transaction
-declare -a FILES
-FILES=$(git diff --cached --name-only --diff-filter=ACM "${revision}")
-for file in ${FILES[@]}
-do
-    # Don't check empty files
-    if [[ $(git cat-file -s ":0:${file}") -eq 0 ]]; then
-        continue
-    fi
+FILES="$(git diff --cached --name-only --diff-filter=ACM "${revision}")"
+for file in "${FILES}" ; do
+  # Don't check empty files
+  if [ $(git cat-file -s ":0:${file}") -eq 0 ]; then
+    continue
+  fi
 
-    extension="${file##*.}"
-    git cat-file blob ":0:${file}" > $TMPFILE
+  extension="${file##*.}"
+  git cat-file blob ":0:${file}" > $TMPFILE
+  rc=$?
+  if [ $rc -ne 0 ]; then
+    echo "Unable to checkout ${file}"
+    STATUS=2
+  else
+    case $extension in
+      pp)
+        # Remove import lines while parsing
+        # http://projects.puppetlabs.com/issues/9670#note-14
+        sed -i -e '/^import / d' $TMPFILE >/dev/null 2>&1
+        # Puppet syntax check
+        puppet parser validate $TMPFILE >/dev/null 2>&1
+        if [ $? -ne 0 ]; then
+          echo "Puppet syntax error in ${file}. Run 'puppet parser validate ${file}'" >&2
+          STATUS=2
+        fi
 
-    if [[ $? -ne 0 ]]; then
-        echo "Unable to checkout ${file}"
-        STATUS=2
-    else
-        case $extension in
-            pp)
-                # Remove import lines while parsing
-                # http://projects.puppetlabs.com/issues/9670#note-14
-                sed -i -e '/^import / d' $TMPFILE >/dev/null 2>&1
-                # Puppet syntax check
-                puppet parser validate $TMPFILE >/dev/null 2>&1
-                if [[ $? -ne 0 ]]; then
-                    echo "Puppet syntax error in ${file}. Run 'puppet parser validate ${file}'" >&2
-                    STATUS=2
-                fi
+        # puppet-lint check
+        puppet-lint $PUPPETLINT_FLAGS --log-format "${file}:%{linenumber} %{KIND} - %{message}" $TMPFILE 2> /dev/null
+        if [ $? -ne 0 ] ; then
+          STATUS=2
+        fi
+      ;;
 
-                # puppet-lint check
-                puppet-lint $PUPPETLINT_FLAGS --log-format "${file}:%{linenumber} %{KIND} - %{message}" $TMPFILE 2> /dev/null
-                if [[ $? -ne 0 ]] ; then
-                    STATUS=2
-                fi
+      erb | rb)
+          # syntax check templates - this doesn't catch a lot of mistakes,
+          # but it should catch gross mistakes
+          erb -P -x -T '-' "${TMPFILE}" | ruby -c > /dev/null 2>&1
+          if [ $? -ne 0 ]; then
+              echo "ERB syntax error in ${file}" >&2
+              STATUS=2
+          fi
+      ;;
 
-                # Fix trailing whitespaces
-                echo "### Fixing whitespaces, if any, in ${file}" >&2
-                sed -i 's/[[:space:]]*$//' $file
-                git add $file
+      sh )
+         check_bash ${TMPFILE} ${file}
+      ;;
+
+      *)
+        case $(file --mime --brief ${file}) in
+          *x-shellscript*)
+            check_bash $file
             ;;
-    
-            erb | rb)
-                # syntax check templates - this doesn't catch a lot of mistakes,
-                # but it should catch gross mistakes
-                erb -P -x -T '-' "${TMPFILE}" | ruby -c > /dev/null 2>&1
-                if [[ $? -ne 0 ]]; then
-                    echo "ERB syntax error in ${file}" >&2
-                    STATUS=2
-                fi
-
-                # Fix trailing whitespaces
-                echo "### Fixing whitespaces, if any, in ${file}" >&2
-                sed -i 's/[[:space:]]*$//' $file
-                git add $file
+          *x-ruby*)
+            ruby -c $x
             ;;
-
-            sh )
-                bash -n $x > /dev/null 2>&1
-
-                # Fix trailing whitespaces
-                echo "### Fixing whitespaces, if any, in ${file}" >&2
-                sed -i 's/[[:space:]]*$//' $file
-                git add $file
+          *x-python*)
+            python -m py_compile $file
             ;;
-
-            *)
-                echo "Skipping ${file}"
+          *x-perl*)
+            perl -c $file
             ;;
         esac
-    fi
+      ;;
+    esac
+
+    fix_trailing_ws_and_stage "${file}"
+  fi
 done
 
 exit $STATUS
-
